# Generated by Django 4.1.2 on 2022-11-27 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comments_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='comments',
            new_name='Comment',
        ),
    ]
